## Import and Clean 1st set of Data = WQ0611

In [4]:
# Import descrepancies
import pandas as pd 
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


In [5]:
# Load the file data into the path
file_path = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/Lake_Sammamish_0611.csv"

# Load the file_path data into dataframe
WQ0611_df = pd.read_csv(file_path, skiprows=12, encoding='unicode_escape', on_bad_lines='skip')

# Show the WQ dataframe 
WQ0611_df.head(10)

CollectDate SampleNum Depth (m)  Ammmonia Nitrogen (mg/L)  \
0  01/06/1994  L2704-18       1.0                      0.02   
1  01/06/1994  L2704-19       5.0                       NaN   
2  01/06/1994  L2704-20      10.0                      0.02   
3  01/06/1994  L2704-21      15.0                       NaN   
4  01/06/1994  L2704-22      20.0                       NaN   
5  01/06/1994  L2704-23      22.5                      0.02   
6  01/06/1994  L2704-18       1.0                      0.02   
7  02/14/1994  L2938-18       1.0                      0.02   
8  02/14/1994  L2938-19       5.0                       NaN   
9  02/14/1994  L2938-20      10.0                      0.02   

  Ammmonia Nitrogen Qualifier*  AN MDL (mg/L)  Conductivity (µmhos/cm)  \
0                   <MDL                 0.02                    103.0   
1                          NaN            NaN                    104.0   
2                   <MDL                 0.02                    102.0   
3                          NaN            NaN                    105.0   
4                          NaN            NaN                    104.0   
5                   <MDL                 0.02                    103.0   
6                   <MDL                 0.02                    103.0   
7                   <MDL                 0.02                    102.5   
8                          NaN            NaN                    103.9   
9                   <MDL                 0.02                    105.0   

  Cond Qualifier*  Cond MDL (µmhos/cm)  Dissolved Oxygen (mg/L)  ...  \
0             NaN                  NaN                     9.15  ...   
1             NaN                  NaN                     8.98  ...   
2             NaN                  NaN                     9.00  ...   
3             NaN                  NaN                     9.21  ...   
4             NaN                  NaN                     9.20  ...   
5             NaN                  NaN                     9.19  ...   
6             NaN                  NaN                     9.15  ...   
7             NaN                  NaN                    10.81  ...   
8             NaN                  NaN                    10.71  ...   
9             NaN                  NaN                    10.71  ...   

  Total Nitrogen (mg/L)  TN Qualifier*  TN MDL (mg/L) Total Phosphorus (mg/L)  \
0                  0.41            NaN           0.05                   0.017   
1                   NaN            NaN            NaN                     NaN   
2                  0.44            NaN           0.05                   0.019   
3                   NaN            NaN            NaN                     NaN   
4                   NaN            NaN            NaN                     NaN   
5                  0.40            NaN           0.05                   0.023   
6                  0.41            NaN           0.05                   0.017   
7                  0.47            NaN           0.05                   0.030   
8                   NaN            NaN            NaN                     NaN   
9                  0.53            NaN           0.05                   0.049   

   TP Qualifier* TP MDL (mg/L)  Total Alkalinity (mg/L)  \
0            NaN         0.005                     42.0   
1            NaN           NaN                      NaN   
2            NaN         0.005                     42.0   
3            NaN           NaN                      NaN   
4            NaN           NaN                      NaN   
5            NaN         0.005                     42.0   
6            NaN         0.005                     42.0   
7            NaN         0.005                      NaN   
8            NaN           NaN                      NaN   
9            NaN         0.005                      NaN   

  Total Alkalinity Qualifier*  Total Alkalinity MDL (mg/L)  Unnamed: 35  
0                         NaN                          0.2          NaN  
1         

In [6]:
WQ0611_df.count()

CollectDate                        10033
SampleNum                          10033
Depth (m)                          10010
Ammmonia Nitrogen (mg/L)            2538
Ammmonia Nitrogen Qualifier*        2199
AN MDL (mg/L)                       2653
Conductivity (µmhos/cm)             8133
Cond Qualifier*                      445
Cond MDL (µmhos/cm)                 6020
Dissolved Oxygen (mg/L)             8052
DO Qualifier*                        809
DO MDL (mg/L)                       6014
Ecoli                                170
Ecoli Qualifier*                       5
Fecal Coliform (CFU/100ml)           316
Fecal Coliform Qualifier*              3
Nitrate Nitrite (mg/L)              2566
Nitrate Nitrite Qualifier*           575
Nitrate Nitrite MDL (mg/L)          2654
Orthophosphate Phosphate (mg/L)     2473
OP Qualifier*                       1790
OP MDL (mg/L)                       2651
pH                                  8139
pH Qualifier*                        433
Temperature (°C)

In [7]:
WQ0611_df.columns

Index(['CollectDate', 'SampleNum', 'Depth (m)', 'Ammmonia Nitrogen (mg/L)',
       'Ammmonia Nitrogen Qualifier*', 'AN MDL (mg/L)',
       'Conductivity (µmhos/cm)', 'Cond Qualifier*', 'Cond MDL (µmhos/cm)',
       'Dissolved Oxygen (mg/L)', 'DO Qualifier*', 'DO MDL (mg/L)', 'Ecoli',
       'Ecoli Qualifier*', 'Fecal Coliform (CFU/100ml)',
       'Fecal Coliform Qualifier*', 'Nitrate Nitrite (mg/L)',
       'Nitrate Nitrite Qualifier*', 'Nitrate Nitrite MDL (mg/L)',
       'Orthophosphate Phosphate (mg/L)', 'OP Qualifier*', 'OP MDL (mg/L)',
       'pH', 'pH Qualifier*', 'Temperature (°C)', 'Temperature Qualifier*',
       'Total Nitrogen (mg/L)', 'TN Qualifier*', 'TN MDL (mg/L)',
       'Total Phosphorus (mg/L)', 'TP Qualifier*', 'TP MDL (mg/L)',
       'Total Alkalinity (mg/L)', 'Total Alkalinity Qualifier*',
       'Total Alkalinity MDL (mg/L)', 'Unnamed: 35'],
      dtype='object')

In [8]:
# columns = [
#     "CollectDate", "SampleNum", "Depth (m)", "Ammmonia Nitrogen (mg/L)", "Ammmonia Nitrogen Qualifier*",
#     "AN MDL (mg/L)", "Conductivity (µmhos/cm)", "Cond Qualifier*", "Cond MDL (µmhos/cm)",
#     "Dissolved Oxygen (mg/L)", "DO Qualifier*", "DO MDL (mg/L)", "Ecoli", "Ecoli Qualifier*", 
#     "Fecal Coliform (CFU/100ml)", "Fecal Coliform Qualifier*", "Nitrate Nitrite (mg/L)", 
#     "Nitrate Nitrite Qualifier*", "Nitrate Nitrite MDL (mg/L)", "Orthophosphate Phosphate (mg/L)", 
#     "OP Qualifier*", "OP MDL (mg/L)", "pH", "pH Qualifier*", "Temperature (°C)", "Temperature Qualifier*", 
#     "Total Nitrogen (mg/L)", "TN Qualifier*", "TN MDL (mg/L)", "Total Phosphorus (mg/L)", "TP Qualifier*", 
#     "TP MDL (mg/L)", "Total Alkalinity (mg/L)", "Total Alkalinity Qualifier*", "Total Alkalinity MDL (mg/L)", 
#     "Unnamed: 35"
# ]

# columns_qualifier = [
#     "Depth (m)", "Ammmonia Nitrogen Qualifier*", "Cond Qualifier*", "DO Qualifier*", 
#     "Ecoli Qualifier*", "Fecal Coliform Qualifier*","Nitrate Nitrite Qualifier*", "OP Qualifier*", 
#     "pH Qualifier*", "Temperature Qualifier*", "TN Qualifier*","TP Qualifier*", "Total Alkalinity Qualifier*"
# ]
# columns_MDL = [
#     "AN MDL (mg/L)", "DO MDL (mg/L)", "Nitrate Nitrite MDL (mg/L)", "OP MDL (mg/L)", 
#     "TN MDL (mg/L)", "TP MDL (mg/L)", "Total Alkalinity MDL (mg/L)"
# ]

In [9]:
# print(columns)
# print(columns_qualifier)
# print(columns_MDL)

In [10]:
# Drop all the qualidiers 
WQ0611_df = WQ0611_df.drop(columns=["Depth (m)", "Ammmonia Nitrogen Qualifier*", "Cond Qualifier*", "DO Qualifier*", 
    "Ecoli Qualifier*", "Fecal Coliform Qualifier*","Nitrate Nitrite Qualifier*", "OP Qualifier*", 
    "pH Qualifier*", "Temperature Qualifier*", "TN Qualifier*","TP Qualifier*", "Total Alkalinity Qualifier*"])

# Drop all the MDL columns
WQ0611_df = WQ0611_df.drop(columns=["AN MDL (mg/L)", "Cond MDL (µmhos/cm)", "DO MDL (mg/L)", "Nitrate Nitrite MDL (mg/L)",
"OP MDL (mg/L)", "TN MDL (mg/L)", "TP MDL (mg/L)", "Total Alkalinity MDL (mg/L)"])

# Drop unnamed columns 
WQ0611_df = WQ0611_df.drop(columns=["Unnamed: 35"])

WQ0611_df = WQ0611_df.drop(columns=["Ecoli", "Total Alkalinity (mg/L)"])

WQ0611_df


CollectDate  SampleNum  Ammmonia Nitrogen (mg/L)  \
0      01/06/1994   L2704-18                      0.02   
1      01/06/1994   L2704-19                       NaN   
2      01/06/1994   L2704-20                      0.02   
3      01/06/1994   L2704-21                       NaN   
4      01/06/1994   L2704-22                       NaN   
...           ...        ...                       ...   
10028  09/13/2022  L80241-37                       NaN   
10029  09/13/2022  L80241-38                       NaN   
10030  09/13/2022  L80241-39                       NaN   
10031  09/13/2022  L80241-40                       NaN   
10032  09/13/2022  L80059-47                       NaN   

       Conductivity (µmhos/cm)  Dissolved Oxygen (mg/L)  \
0                        103.0                     9.15   
1                        104.0                     8.98   
2                        102.0                     9.00   
3                        105.0                     9.21   
4                        104.0                     9.20   
...                        ...                      ...   
10028                    105.7                     3.27   
10029                    106.3                     2.12   
10030                    107.3                     1.02   
10031                    107.5                     0.79   
10032                      NaN                      NaN   

       Fecal Coliform (CFU/100ml)  Nitrate Nitrite (mg/L)  \
0                             1.0                    0.27   
1                             NaN                     NaN   
2                             NaN                    0.29   
3                             NaN                     NaN   
4                             NaN                     NaN   
...                           ...                     ...   
10028                         NaN                     NaN   
10029                         NaN                     NaN   
10030                         NaN                     NaN   
10031                         NaN                     NaN   
10032                         NaN                     NaN   

       Orthophosphate Phosphate (mg/L)   pH  Temperature (°C)  \
0                                0.011  7.4               7.4   
1                                  NaN  7.4               7.3   
2                                0.012  7.4               7.3   
3                                  NaN  7.4               7.3   
4                                  NaN  7.4               7.3   
...                                ...  ...               ...   
10028                              NaN  6.6               9.8   
10029                              NaN  6.5               9.4   
10030                              NaN  6.4               9.2   
10031                              NaN  6.4               9.2   
10032                              NaN  NaN               NaN   

       Total Nitrogen (mg/L)  Total Phosphorus (mg/L)  
0                      0.410                    0.017  
1                        NaN                      NaN  
2                      0.440                    0.019  
3                        NaN                      NaN  
4                        NaN                      NaN  
...                      ...                      ...  
10028                    NaN                      NaN  
10029                    NaN                      NaN  
10030                    NaN                      NaN  
10031                    NaN                      NaN  
10032                  0.184                      NaN  

[10033 rows x 12 columns]

In [11]:
WQ0611_df.count()

CollectDate                        10033
SampleNum                          10033
Ammmonia Nitrogen (mg/L)            2538
Conductivity (µmhos/cm)             8133
Dissolved Oxygen (mg/L)             8052
Fecal Coliform (CFU/100ml)           316
Nitrate Nitrite (mg/L)              2566
Orthophosphate Phosphate (mg/L)     2473
pH                                  8139
Temperature (°C)                    8155
Total Nitrogen (mg/L)               2647
Total Phosphorus (mg/L)             2746
dtype: int64

In [12]:
# Checking unique values for columns. 
print(WQ0611_df["Ammmonia Nitrogen (mg/L)"].unique())
print(WQ0611_df["Nitrate Nitrite (mg/L)"].unique())
print(WQ0611_df["Orthophosphate Phosphate (mg/L)"].unique())
print(WQ0611_df["Total Nitrogen (mg/L)"].unique())
print(WQ0611_df["Total Phosphorus (mg/L)"].unique())
print(WQ0611_df["Ecoli"].unique())
print(WQ0611_df["Fecal Coliform (CFU/100ml)"].unique())


[0.02    nan 0.06  0.054 0.05  0.107 0.144 0.179 0.191 0.238 0.03  0.028
 0.125 0.135 0.033 0.031 0.217 0.232 0.025 0.024 0.023 0.029 0.035 0.027
 0.026 0.022 0.034 0.037 0.063 0.032 0.081 0.101 0.047 0.039 0.042 0.021
 0.077 0.117 0.036 0.013 0.014 0.01  0.016 0.041 0.076 0.123 0.018 0.055
 0.178 0.112 0.2   0.015 0.017 0.045 0.012 0.053 0.044 0.058 0.011 0.061
 0.113 0.019 0.046 0.085 0.084 0.057 0.048 0.052 0.174 0.195 0.202 0.056
 0.321 0.227 0.082 0.067 0.043 0.114 0.088 0.104 0.169 0.04  0.072 0.096
 0.105 0.134 0.066 0.11  0.078 0.129 0.064 0.116 0.143 0.005 0.007 0.006
 0.008 0.038 0.009 0.079 0.093 0.188 0.185 0.068 0.051 0.106 0.002 0.003
 0.07  0.004 0.187 0.201 0.211 0.172 0.182 0.189 0.109 0.204 0.12  0.205
 0.221 0.254 0.294 0.142 0.062 0.049 0.073 0.253 0.148 0.094]
[0.27    nan 0.29  0.28  0.31  0.26  0.32  0.38  0.223 0.276 0.36  0.241
 0.252 0.341 0.251 0.326 0.264 0.312 0.247 0.266 0.214 0.14  0.233 0.221
 0.05  0.129 0.205 0.22  0.199 0.147 0.15  0.151 0.319 0.356 0

KeyError: 'Ecoli'

In [13]:
# convert string to datetime
WQ0611_df["CollectDate"] = pd.to_datetime(WQ0611_df["CollectDate"])

In [14]:
WQ0611_df.dtypes

CollectDate                        datetime64[ns]
SampleNum                                  object
Ammmonia Nitrogen (mg/L)                  float64
Conductivity (µmhos/cm)                   float64
Dissolved Oxygen (mg/L)                   float64
Fecal Coliform (CFU/100ml)                float64
Nitrate Nitrite (mg/L)                    float64
Orthophosphate Phosphate (mg/L)           float64
pH                                        float64
Temperature (°C)                          float64
Total Nitrogen (mg/L)                     float64
Total Phosphorus (mg/L)                   float64
dtype: object

In [15]:
df_1 = WQ0611_df 

In [31]:
df_2 = df_1.groupby(["CollectDate"]).apply(lambda x:x.fillna(x.mean()))
df_2.head(10)

CollectDate SampleNum  Ammmonia Nitrogen (mg/L)  Conductivity (µmhos/cm)  \
0  1994-01-06  L2704-18                      0.02                    103.0   
1  1994-01-06  L2704-19                      0.02                    104.0   
2  1994-01-06  L2704-20                      0.02                    102.0   
3  1994-01-06  L2704-21                      0.02                    105.0   
4  1994-01-06  L2704-22                      0.02                    104.0   
5  1994-01-06  L2704-23                      0.02                    103.0   
6  1994-01-06  L2704-18                      0.02                    103.0   
7  1994-02-14  L2938-18                      0.02                    102.5   
8  1994-02-14  L2938-19                      0.02                    103.9   
9  1994-02-14  L2938-20                      0.02                    105.0   

   Dissolved Oxygen (mg/L)  Fecal Coliform (CFU/100ml)  \
0                     9.15                         1.0   
1                     8.98                         1.0   
2                     9.00                         1.0   
3                     9.21                         1.0   
4                     9.20                         1.0   
5                     9.19                         1.0   
6                     9.15                         1.0   
7                    10.81                         7.0   
8                    10.71                         7.0   
9                    10.71                         7.0   

   Nitrate Nitrite (mg/L)  Orthophosphate Phosphate (mg/L)   pH  \
0                  0.2700                          0.01100  7.4   
1                  0.2775                          0.01175  7.4   
2                  0.2900                          0.01200  7.4   
3                  0.2775                          0.01175  7.4   
4                  0.2775                          0.01175  7.4   
5                  0.2800                          0.01300  7.4   
6                  0.2700                          0.01100  7.4   
7                  0.3100                          0.00900  7.4   
8                  0.3000                          0.00900  7.4   
9                  0.2600                          0.00900  7.4   

   Temperature (°C)  Total Nitrogen (mg/L)  Total Phosphorus (mg/L)  
0               7.4                 0.4100                   0.0170  
1               7.3                 0.4150                   0.0190  
2               7.3                 0.4400                   0.0190  
3               7.3                 0.4150                   0.0190  
4               7.3                 0.4150                   0.0190  
5               7.3                 0.4000                   0.0230  
6               7.4                 0.4100                   0.0170  
7               6.5                 0.4700                   0.0300  
8               6.5                 0.4925                   0.0345  
9               6.5                 0.5300                   0.0490

In [32]:
# Removing the SampleNum column
df_2 = df_2.drop(columns=["SampleNum"])


In [33]:
df_2.isnull().sum()

CollectDate                           0
Ammmonia Nitrogen (mg/L)           1491
Conductivity (µmhos/cm)              69
Dissolved Oxygen (mg/L)              81
Fecal Coliform (CFU/100ml)         7009
Nitrate Nitrite (mg/L)             1372
Orthophosphate Phosphate (mg/L)    1469
pH                                   63
Temperature (°C)                     50
Total Nitrogen (mg/L)              1407
Total Phosphorus (mg/L)              93
dtype: int64

In [34]:
df_2.count()

CollectDate                        10033
Ammmonia Nitrogen (mg/L)            8542
Conductivity (µmhos/cm)             9964
Dissolved Oxygen (mg/L)             9952
Fecal Coliform (CFU/100ml)          3024
Nitrate Nitrite (mg/L)              8661
Orthophosphate Phosphate (mg/L)     8564
pH                                  9970
Temperature (°C)                    9983
Total Nitrogen (mg/L)               8626
Total Phosphorus (mg/L)             9940
dtype: int64

In [35]:
# Drop Nan column
df_3 = df_2.dropna()
df_3.count()

CollectDate                        3015
Ammmonia Nitrogen (mg/L)           3015
Conductivity (µmhos/cm)            3015
Dissolved Oxygen (mg/L)            3015
Fecal Coliform (CFU/100ml)         3015
Nitrate Nitrite (mg/L)             3015
Orthophosphate Phosphate (mg/L)    3015
pH                                 3015
Temperature (°C)                   3015
Total Nitrogen (mg/L)              3015
Total Phosphorus (mg/L)            3015
dtype: int64

In [36]:
df_3.columns

Index(['CollectDate', 'Ammmonia Nitrogen (mg/L)', 'Conductivity (µmhos/cm)',
       'Dissolved Oxygen (mg/L)', 'Fecal Coliform (CFU/100ml)',
       'Nitrate Nitrite (mg/L)', 'Orthophosphate Phosphate (mg/L)', 'pH',
       'Temperature (°C)', 'Total Nitrogen (mg/L)', 'Total Phosphorus (mg/L)'],
      dtype='object')

In [20]:
# Pretend calculation

# df_3['WQI'] = (df_3['Ammmonia Nitrogen (mg/L)'] + df_3['Conductivity (µmhos/cm)'] 
# + df_3['Dissolved Oxygen (mg/L)'] + df_3['Fecal Coliform (CFU/100ml)'] 
# + df_3['Nitrate Nitrite (mg/L)'] + df_3['Orthophosphate Phosphate (mg/L)'] 
# + df_3['pH'] + df_3['Temperature (°C)'] + df_3['Total Nitrogen (mg/L)'] 
# + df_3['Total Phosphorus (mg/L)'])

# df_3.head()

In [37]:
# Water Quality Index Calculation 

# Standard deviation for each parameter
amm_Sn = 0.1
cond_Sn = 300
dis_ox_Sn = 5.5
fec_coli_Sn = 135
nit_nit_Sn = 0.1
orth_phos_Sn = 0.5
pH_Sn = 8.5
temp_Sn = 7
tot_nit_Sn = 1.2
tot_phos_Sn = 0.1

# Inverse of Standard values for each parameter/feature, colC
inv_amm = 1/amm_Sn
inv_cond = 1/cond_Sn
inv_dis_ox = 1/dis_ox_Sn
inv_fec_coli_Sn = 1/fec_coli_Sn
inv_nit_nit = 1/nit_nit_Sn
inv_orth_phos = 1/orth_phos_Sn
inv_pH = 1/pH_Sn
inv_temp = 1/temp_Sn
inv_tot_nit = 1/tot_nit_Sn
inv_tot_phos = 1/tot_phos_Sn

# Sum of all inverses of standard values, colD
sum_all_inv = inv_amm + inv_cond + inv_dis_ox + inv_fec_coli_Sn + inv_nit_nit + inv_orth_phos + inv_pH + inv_temp + inv_tot_nit + inv_tot_phos

# K is the inverse of the sum of all inverses, colE
K = 1/sum_all_inv

# Wn is K divided by the standard value for each parameter/feature, colF
amm_Wn = K / amm_Sn
cond_Wn = K / cond_Sn
dis_ox_Wn = K / dis_ox_Sn
fec_coli_Wn = K / fec_coli_Sn
nit_nit_Wn = K / nit_nit_Sn
orth_phos_Wn = K / orth_phos_Sn
pH_Wn = K / pH_Sn
temp_Wn = K / temp_Sn
tot_nit_Wn = K / tot_nit_Sn
tot_phos_Wn = K / tot_phos_Sn

# Water Quality Index
# test = ((((df_3.loc[0]['Ammmonia Nitrogen (mg/L)']/amm_Sn)*100)*amm_Wn) + (((df_3.loc[0]['Conductivity (µmhos/cm)']/cond_Sn)*100)*cond_Wn)) + (((df_3.loc[0]['Dissolved Oxygen (mg/L)']/dis_ox_Sn)*100)*dis_ox_Wn) + (((df_3.loc[0]['Fecal Coliform (CFU/100ml)']/fec_coli_Sn)*100)*fec_coli_Wn) + (((df_3.loc[0]['Nitrate Nitrite (mg/L)']/nit_nit_Sn)*100)*nit_nit_Wn) + (((df_3.loc[0]['Orthophosphate Phosphate (mg/L)']/orth_phos_Sn)*100)*orth_phos_Wn) + (((df_3.loc[0]['pH']/pH_Sn)*100)*pH_Wn) + (((df_3.loc[0]['Temperature (°C)']/temp_Sn)*100)*temp_Wn) + (((df_3.loc[0]['Total Nitrogen (mg/L)']/tot_nit_Sn)*100)*tot_nit_Wn) + (((df_3.loc[0]['Total Phosphorus (mg/L)']/tot_phos_Sn)*100)*tot_phos_Wn)
# test

df_3['WQI'] = ((((df_3['Ammmonia Nitrogen (mg/L)']/amm_Sn)*100)*amm_Wn) + (((df_3['Conductivity (µmhos/cm)']/cond_Sn)*100)*cond_Wn)) + (((df_3['Dissolved Oxygen (mg/L)']/dis_ox_Sn)*100)*dis_ox_Wn) + (((df_3['Fecal Coliform (CFU/100ml)']/fec_coli_Sn)*100)*fec_coli_Wn) + (((df_3['Nitrate Nitrite (mg/L)']/nit_nit_Sn)*100)*nit_nit_Wn) + (((df_3['Orthophosphate Phosphate (mg/L)']/orth_phos_Sn)*100)*orth_phos_Wn) + (((df_3['pH']/pH_Sn)*100)*pH_Wn) + (((df_3['Temperature (°C)']/temp_Sn)*100)*temp_Wn) + (((df_3['Total Nitrogen (mg/L)']/tot_nit_Sn)*100)*tot_nit_Wn) + (((df_3['Total Phosphorus (mg/L)']/tot_phos_Sn)*100)*tot_phos_Wn)
df_3.head()

/Users/linghoang/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:49: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy


CollectDate  Ammmonia Nitrogen (mg/L)  Conductivity (µmhos/cm)  \
0  1994-01-06                      0.02                    103.0   
1  1994-01-06                      0.02                    104.0   
2  1994-01-06                      0.02                    102.0   
3  1994-01-06                      0.02                    105.0   
4  1994-01-06                      0.02                    104.0   

   Dissolved Oxygen (mg/L)  Fecal Coliform (CFU/100ml)  \
0                     9.15                         1.0   
1                     8.98                         1.0   
2                     9.00                         1.0   
3                     9.21                         1.0   
4                     9.20                         1.0   

   Nitrate Nitrite (mg/L)  Orthophosphate Phosphate (mg/L)   pH  \
0                  0.2700                          0.01100  7.4   
1                  0.2775                          0.01175  7.4   
2                  0.2900                          0.01200  7.4   
3                  0.2775                          0.01175  7.4   
4                  0.2775                          0.01175  7.4   

   Temperature (°C)  Total Nitrogen (mg/L)  Total Phosphorus (mg/L)  \
0               7.4                  0.410                    0.017   
1               7.3                  0.415                    0.019   
2               7.3                  0.440                    0.019   
3               7.3                  0.415                    0.019   
4               7.3                  0.415                    0.019   

          WQI  
0   94.891147  
1   97.741629  
2  101.553997  
3   97.764504  
4   97.763478

In [38]:
import numpy as np

In [39]:
WQI_Conditions = [
    (df_3['WQI'] <= 25),
    (df_3['WQI'] >= 26) & (df_3['WQI'] <= 50),
    (df_3['WQI'] >= 51) & (df_3['WQI'] <= 75),
    (df_3['WQI'] >= 76) & (df_3['WQI'] <= 90),
    (df_3['WQI'] >= 91) & (df_3['WQI'] <= 100)
]

WQI_Categories = ['0', '1', '2', '3', '4']

df_3['WQ'] = np.select(WQI_Conditions, WQI_Categories) 

df_3.head(50)



/Users/linghoang/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/ipykernel_launcher.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()


CollectDate  Ammmonia Nitrogen (mg/L)  Conductivity (µmhos/cm)  \
0   1994-01-06                      0.02                    103.0   
1   1994-01-06                      0.02                    104.0   
2   1994-01-06                      0.02                    102.0   
3   1994-01-06                      0.02                    105.0   
4   1994-01-06                      0.02                    104.0   
5   1994-01-06                      0.02                    103.0   
6   1994-01-06                      0.02                    103.0   
7   1994-02-14                      0.02                    102.5   
8   1994-02-14                      0.02                    103.9   
9   1994-02-14                      0.02                    105.0   
10  1994-02-14                      0.02                    105.2   
11  1994-02-14                      0.02                    105.2   
12  1994-02-14                      0.02                    105.5   
13  1994-02-14                      0.02                    102.5   
14  1994-03-08                      0.02                    103.4   
15  1994-03-08                      0.02                    104.0   
16  1994-03-08                      0.02                    105.1   
17  1994-03-08                      0.02                    105.3   
18  1994-03-08                      0.02                    105.9   
19  1994-03-08                      0.02                    105.3   
20  1994-03-08                      0.02                    103.4   
21  1994-03-22                      0.02                    104.0   
22  1994-03-22                      0.02                    105.3   
23  1994-03-22                      0.02                    105.9   
24  1994-03-22                      0.02                    106.2   
25  1994-03-22                      0.02                    106.3   
26  1994-03-22                      0.02                    106.5   
27  1994-03-22                      0.02                    104.0   
28  1994-04-05                      0.02                    103.7   
29  1994-04-05                      0.02                    104.2   
30  1994-04-05                      0.02                    103.3   
31  1994-04-05                      0.02                    103.3   
32  1994-04-05                      0.02                    103.7   
33  1994-04-05                      0.02                    103.9   
34  1994-04-05                      0.02                    103.7   
35  1994-04-19                      0.02                    104.5   
36  1994-04-19                      0.02                    105.0   
37  1994-04-19                      0.02                    103.9   
38  1994-04-19                      0.02                    103.6   
39  1994-04-19                      0.02                    104.1   
40  1994-04-19                      0.02                    104.1   
41  1994-04-19                      0.02                    104.5   
42  1994-05-03                      0.02                    108.3   
43  1994-05-03                      0.02                    108.5   
44  1994-05-03                      0.02                    107.0   
45  1994-05-03                      0.02                    106.6   
46  1994-05-03                      0.02                    106.3   
47  1994-05-03                      0.02                    106.4   
48  1994-05-03                      0.02                    108.3   
49  1994-05-24                      0.02                    114.1   

    Dissolved Oxygen (mg/L)  Fecal Coliform (CFU/100ml)  \
0                      9.15                         1.0   
1                      8.98                         1.0   
2                      9.00                         1.0   
3                      9.21                         1.0   
4                      9.20                         1.0   
5                      9.19                         1.0   
6                      9.15                         1.0   
7          

In [40]:
# Export csv file 

path = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/Output/Lake_Sammamish_0611_clean.csv"
df_3.to_csv(path, index=False)

## Set Up Logistic Regression Model 

In [47]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LogisticRegression

In [48]:
# Seperate the Features (X) from the Target (y)
y = df_3['WQ']
X = df_3.drop(['WQ', 'CollectDate'], axis='columns')


In [49]:
# Split our data into training and testing 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=42)
                                                    
                                                    
X_train.shape

(2261, 11)

In [50]:
y_train

3476    0
2784    2
100     1
315     0
892     0
       ..
2224    0
1323    0
1358    4
1619    0
927     0
Name: WQ, Length: 2261, dtype: object

In [51]:
y_test

63      4
3842    3
102     1
3850    3
416     0
       ..
698     0
3810    2
924     0
238     0
2148    0
Name: WQ, Length: 754, dtype: object

In [53]:
# Create a Logistic Regression Model 

classifier = LogisticRegression(solver='lbfgs', random_state=0)
classifier

LogisticRegression(random_state=0)

In [54]:
classifier.fit(X_train, y_train)

/Users/linghoang/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

In [55]:
from sklearn import preprocessing
from sklearn import utils

In [56]:
# convert y values to categorical values
lab = preprocessing.LabelEncoder()
y_transformed = lab.fit_transform(y)

In [57]:
#view transformed values (1)
print(y_transformed)

[4 4 0 ... 2 2 0]


In [58]:
# Fit (train) or model using the training data 
classifier.fit(X, y_transformed)

/Users/linghoang/opt/anaconda3/envs/mlenv/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

In [59]:
# Prediction outcomes for test data set 
predictions = classifier.predict(X_test)

results = pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)
results.head(20)

Prediction Actual
0            0      4
1            0      3
2            2      1
3            0      3
4            0      0
5            1      1
6            2      2
7            2      2
8            0      0
9            0      0
10           2      4
11           0      0
12           1      1
13           2      0
14           0      0
15           2      0
16           0      0
17           2      0
18           0      4
19           0      4

In [61]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, predictions))

0.0


## Set up Random Forest Model to make Classification 

In [62]:
# Initials imports
import pandas as pd
from pathlib import Path
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


In [77]:
# Loading data
file_path = Path("/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/OutPut/Lake_Sammamish_0611_clean.csv")
WQ0611_clean_df = pd.read_csv(file_path)
WQ0611_clean_df.head()

CollectDate  Ammmonia Nitrogen (mg/L)  Conductivity (µmhos/cm)  \
0  1994-01-06                      0.02                    103.0   
1  1994-01-06                      0.02                    104.0   
2  1994-01-06                      0.02                    102.0   
3  1994-01-06                      0.02                    105.0   
4  1994-01-06                      0.02                    104.0   

   Dissolved Oxygen (mg/L)  Fecal Coliform (CFU/100ml)  \
0                     9.15                         1.0   
1                     8.98                         1.0   
2                     9.00                         1.0   
3                     9.21                         1.0   
4                     9.20                         1.0   

   Nitrate Nitrite (mg/L)  Orthophosphate Phosphate (mg/L)   pH  \
0                  0.2700                          0.01100  7.4   
1                  0.2775                          0.01175  7.4   
2                  0.2900                          0.01200  7.4   
3                  0.2775                          0.01175  7.4   
4                  0.2775                          0.01175  7.4   

   Temperature (°C)  Total Nitrogen (mg/L)  Total Phosphorus (mg/L)  \
0               7.4                  0.410                    0.017   
1               7.3                  0.415                    0.019   
2               7.3                  0.440                    0.019   
3               7.3                  0.415                    0.019   
4               7.3                  0.415                    0.019   

          WQI  WQ  
0   94.891147   4  
1   97.741629   4  
2  101.553997   0  
3   97.764504   4  
4   97.763478   4

In [78]:
## Preprocess the Data

In [75]:
# Define the features set
X = WQ0611_clean_df.copy()
X = X.drop(['WQ','CollectDate'], axis='columns')
X.head()

Ammmonia Nitrogen (mg/L)  Conductivity (µmhos/cm)  Dissolved Oxygen (mg/L)  \
0                      0.02                    103.0                     9.15   
1                      0.02                    104.0                     8.98   
2                      0.02                    102.0                     9.00   
3                      0.02                    105.0                     9.21   
4                      0.02                    104.0                     9.20   

   Fecal Coliform (CFU/100ml)  Nitrate Nitrite (mg/L)  \
0                         1.0                  0.2700   
1                         1.0                  0.2775   
2                         1.0                  0.2900   
3                         1.0                  0.2775   
4                         1.0                  0.2775   

   Orthophosphate Phosphate (mg/L)   pH  Temperature (°C)  \
0                          0.01100  7.4               7.4   
1                          0.01175  7.4               7.3   
2                          0.01200  7.4               7.3   
3                          0.01175  7.4               7.3   
4                          0.01175  7.4               7.3   

   Total Nitrogen (mg/L)  Total Phosphorus (mg/L)         WQI  
0                  0.410                    0.017   94.891147  
1                  0.415                    0.019   97.741629  
2                  0.440                    0.019  101.553997  
3                  0.415                    0.019   97.764504  
4                  0.415                    0.019   97.763478

In [79]:
# Define the target set.
y = WQ0611_clean_df["WQ"].ravel()
y[:5]

array([4, 4, 0, 4, 4])

In [80]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [81]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [86]:
X_train_scaled

array([[-0.54063912, -0.27153495,  0.48439841, ...,  1.1135104 ,
        -0.1157638 ,  1.2299974 ],
       [-0.05300265,  0.27976825,  0.04246591, ...,  0.0579495 ,
        -0.69461786,  0.19489828],
       [ 0.19081559, -0.10447338,  0.01530805, ...,  0.01362148,
         0.79919908,  0.11915783],
       ...,
       [-0.52438457, -0.10447338, -0.84880578, ..., -0.44489644,
         0.22501319, -0.60680288],
       [ 0.53912736, -0.87295663, -1.15001117, ..., -0.00141838,
        -0.16111181,  0.11312837],
       [-0.54063912, -1.15696131,  0.9287998 , ...,  0.34054061,
        -0.34606058,  0.14707248]])

In [87]:
X_test_scaled

array([[ 0.19081559, -2.15933078,  0.05481039, ..., -0.57372474,
        -0.09709109, -0.752157  ],
       [-0.54063912,  0.65287244,  0.44489606, ..., -0.74826631,
        -0.8346632 , -0.43431322],
       [-0.54063912,  0.83107146,  0.30416895, ...,  1.05532988,
         0.16432688,  1.32598619],
       ...,
       [-0.05300265, -0.30494727,  0.55846531, ...,  0.63619265,
        -0.80131907,  0.28808147],
       [-0.29682088,  1.34339363, -1.05886773, ..., -0.88956186,
        -0.27448185, -1.49594302],
       [-0.05300265,  1.86685323,  0.39798703, ..., -0.59658137,
        -0.34450452, -0.50401694]])

In [88]:
y_train

array([0, 4, 4, ..., 2, 4, 4])

In [89]:
y_test

array([2, 2, 0, 0, 4, 4, 0, 0, 2, 1, 3, 0, 2, 0, 0, 2, 2, 0, 2, 2, 2, 0,
       4, 2, 2, 0, 0, 3, 4, 2, 0, 4, 0, 1, 2, 2, 1, 0, 2, 3, 1, 4, 3, 0,
       0, 2, 3, 4, 2, 1, 4, 2, 0, 0, 2, 0, 0, 3, 3, 2, 1, 0, 2, 2, 2, 3,
       3, 0, 0, 0, 2, 0, 1, 3, 3, 3, 0, 0, 2, 0, 0, 2, 0, 3, 2, 3, 2, 3,
       0, 3, 2, 0, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0, 2, 0, 0, 0, 2, 4, 0, 2,
       0, 1, 0, 0, 0, 2, 0, 3, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 1, 0, 2,
       3, 0, 0, 4, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1, 3, 3, 0, 0, 2, 4, 0, 0,
       0, 0, 2, 1, 0, 0, 1, 2, 1, 0, 0, 0, 1, 0, 2, 1, 1, 0, 0, 2, 0, 2,
       3, 2, 0, 0, 2, 2, 0, 0, 3, 1, 3, 0, 4, 0, 0, 3, 3, 0, 0, 2, 0, 1,
       4, 0, 0, 0, 2, 0, 3, 0, 3, 0, 0, 0, 0, 0, 3, 2, 3, 2, 3, 2, 2, 0,
       4, 0, 2, 0, 1, 0, 2, 4, 0, 1, 3, 2, 0, 0, 2, 2, 0, 4, 2, 0, 0, 0,
       2, 0, 0, 3, 3, 1, 2, 1, 2, 0, 0, 2, 2, 0, 3, 1, 0, 0, 0, 3, 2, 2,
       0, 0, 3, 2, 2, 0, 3, 0, 2, 1, 0, 3, 0, 1, 0, 3, 0, 0, 0, 1, 0, 4,
       0, 3, 4, 0, 0, 0, 3, 4, 0, 2, 4, 4, 2, 4, 2,

In [90]:
# Fit the random forest classidier
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 

In [91]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [92]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [93]:
predictions

array([2, 2, 0, 0, 4, 4, 0, 0, 2, 1, 3, 0, 2, 0, 0, 2, 2, 0, 2, 2, 2, 0,
       4, 2, 2, 0, 0, 3, 4, 2, 0, 4, 0, 1, 2, 2, 1, 0, 2, 3, 1, 4, 3, 0,
       0, 2, 3, 4, 2, 1, 4, 2, 0, 0, 2, 0, 0, 3, 3, 2, 1, 0, 2, 2, 2, 3,
       3, 0, 0, 0, 2, 0, 1, 3, 3, 3, 0, 0, 2, 0, 0, 2, 0, 3, 2, 3, 2, 3,
       0, 3, 2, 0, 0, 2, 0, 0, 2, 0, 1, 0, 2, 0, 2, 0, 0, 0, 2, 4, 0, 2,
       0, 1, 0, 0, 0, 2, 0, 3, 2, 0, 0, 0, 0, 0, 2, 0, 2, 2, 0, 1, 0, 2,
       3, 0, 0, 4, 0, 2, 0, 0, 0, 0, 0, 2, 0, 1, 3, 3, 0, 0, 2, 4, 0, 0,
       0, 0, 2, 1, 0, 0, 1, 2, 1, 0, 0, 0, 1, 0, 2, 1, 1, 0, 0, 2, 0, 2,
       3, 2, 0, 0, 2, 2, 0, 0, 3, 1, 3, 0, 4, 0, 0, 3, 3, 0, 0, 2, 0, 1,
       4, 0, 0, 0, 2, 0, 3, 0, 3, 0, 0, 4, 0, 0, 3, 2, 3, 2, 3, 2, 2, 0,
       4, 0, 2, 0, 1, 0, 2, 4, 0, 1, 3, 2, 0, 0, 2, 2, 0, 4, 2, 0, 0, 0,
       2, 0, 0, 3, 3, 1, 2, 1, 2, 0, 0, 2, 2, 0, 3, 1, 0, 0, 0, 3, 2, 2,
       0, 0, 3, 2, 2, 0, 3, 0, 2, 1, 0, 3, 0, 1, 0, 3, 0, 0, 0, 1, 0, 4,
       0, 3, 4, 0, 0, 0, 3, 4, 0, 2, 4, 4, 2, 4, 2,

In [100]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual"], columns=["Predicted"])

cm_df

ValueError: Shape of passed values is (5, 5), indices imply (1, 1)

In [101]:
print(cm)

[[311   1   0   1   2]
 [  0  66   0   0   0]
 [  0   0 215   0   0]
 [  0   0   0  92   0]
 [  0   0   0   0  66]]


In [102]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)# Displaying results
print("Confusion Matrix")
# display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix
Accuracy Score : 0.9946949602122016
Classification Report
              precision    recall  f1-score   support

           0       1.00      0.99      0.99       315
           1       0.99      1.00      0.99        66
           2       1.00      1.00      1.00       215
           3       0.99      1.00      0.99        92
           4       0.97      1.00      0.99        66

    accuracy                           0.99       754
   macro avg       0.99      1.00      0.99       754
weighted avg       0.99      0.99      0.99       754



In [98]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.03072824, 0.01638334, 0.0207656 , 0.00820667, 0.25924087,
       0.02094566, 0.00917108, 0.02604531, 0.13115642, 0.02674242,
       0.45061439])

In [99]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.4506143947348024, 'WQI'),
 (0.2592408725805396, 'Nitrate Nitrite (mg/L)'),
 (0.1311564249927204, 'Total Nitrogen (mg/L)'),
 (0.030728241100141895, 'Ammmonia Nitrogen (mg/L)'),
 (0.02674241825562615, 'Total Phosphorus (mg/L)'),
 (0.026045306144348992, 'Temperature (°C)'),
 (0.02094565595260851, 'Orthophosphate Phosphate (mg/L)'),
 (0.020765598455236175, 'Dissolved Oxygen (mg/L)'),
 (0.016383335740950255, 'Conductivity (µmhos/cm)'),
 (0.009171080441464047, 'pH'),
 (0.00820667160156146, 'Fecal Coliform (CFU/100ml)')]