## Logistic Regression 

In [1]:
# Import descrepancies
import pandas as pd 
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression


In [3]:
# Load the file data into the path
file_path = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/OutPut/Big_Lake.csv"

# Load the file_path data into dataframe
Big_Lake_df = pd.read_csv(file_path)

# Show the WQ dataframe 
Big_Lake_df.head(10)

CollectDate  Ammmonia Nitrogen (mg/L)  Conductivity (µmhos/cm)  \
0  1994-01-06                      0.02                    103.0   
1  1994-01-06                      0.02                    104.0   
2  1994-01-06                      0.02                    102.0   
3  1994-01-06                      0.02                    105.0   
4  1994-01-06                      0.02                    104.0   
5  1994-01-06                      0.02                    103.0   
6  1994-02-14                      0.02                    102.5   
7  1994-02-14                      0.02                    103.9   
8  1994-02-14                      0.02                    105.0   
9  1994-02-14                      0.02                    105.2   

   Dissolved Oxygen (mg/L)  Fecal Coliform (CFU/100ml)  \
0                     9.15                         1.0   
1                     8.98                         1.0   
2                     9.00                         1.0   
3                     9.21                         1.0   
4                     9.20                         1.0   
5                     9.19                         1.0   
6                    10.81                         7.0   
7                    10.71                         7.0   
8                    10.71                         7.0   
9                    10.65                         7.0   

   Nitrate Nitrite (mg/L)  Orthophosphate Phosphate (mg/L)   pH  \
0                0.270000                            0.011  7.4   
1                0.280000                            0.012  7.4   
2                0.290000                            0.012  7.4   
3                0.280000                            0.012  7.4   
4                0.280000                            0.012  7.4   
5                0.280000                            0.013  7.4   
6                0.310000                            0.009  7.4   
7                0.296667                            0.009  7.4   
8                0.260000                            0.009  7.4   
9                0.296667                            0.009  7.4   

   Temperature (°C)  Total Nitrogen (mg/L)  Total Phosphorus (mg/L)  \
0               7.4               0.410000                 0.017000   
1               7.3               0.416667                 0.019667   
2               7.3               0.440000                 0.019000   
3               7.3               0.416667                 0.019667   
4               7.3               0.416667                 0.019667   
5               7.3               0.400000                 0.023000   
6               6.5               0.470000                 0.030000   
7               6.5               0.500000                 0.036000   
8               6.5               0.530000                 0.049000   
9               6.5               0.500000                 0.036000   

          WQI  WQ  
0   94.891147   4  
1   98.699450   4  
2  101.553997   5  
3   98.722325   4  
4   98.721299   4  
5   99.698928   4  
6  111.025363   5  
7  108.874964   5  
8  101.827577   5  
9  108.869049   5

In [4]:
Big_Lake_df.columns

Index(['CollectDate', 'Ammmonia Nitrogen (mg/L)', 'Conductivity (µmhos/cm)',
       'Dissolved Oxygen (mg/L)', 'Fecal Coliform (CFU/100ml)',
       'Nitrate Nitrite (mg/L)', 'Orthophosphate Phosphate (mg/L)', 'pH',
       'Temperature (°C)', 'Total Nitrogen (mg/L)', 'Total Phosphorus (mg/L)',
       'WQI', 'WQ'],
      dtype='object')

In [5]:
Big_Lake_df = Big_Lake_df.drop(columns=["Unnamed: 0"])

KeyError: "['Unnamed: 0'] not found in axis"

In [6]:
Big_Lake_df

CollectDate  Ammmonia Nitrogen (mg/L)  Conductivity (µmhos/cm)  \
0     1994-01-06                      0.02                   103.00   
1     1994-01-06                      0.02                   104.00   
2     1994-01-06                      0.02                   102.00   
3     1994-01-06                      0.02                   105.00   
4     1994-01-06                      0.02                   104.00   
...          ...                       ...                      ...   
9508  2008-12-09                      0.01                   103.00   
9509  2008-12-09                      0.01                   102.00   
9510  2008-12-09                      0.01                   102.00   
9511  2008-12-09                      0.01                   102.25   
9512  2008-12-09                      0.01                   102.00   

      Dissolved Oxygen (mg/L)  Fecal Coliform (CFU/100ml)  \
0                        9.15                         1.0   
1                        8.98                         1.0   
2                        9.00                         1.0   
3                        9.21                         1.0   
4                        9.20                         1.0   
...                       ...                         ...   
9508                     8.00                        37.0   
9509                     7.90                        37.0   
9510                     7.80                        37.0   
9511                     7.90                        37.0   
9512                     7.90                        37.0   

      Nitrate Nitrite (mg/L)  Orthophosphate Phosphate (mg/L)     pH  \
0                      0.270                         0.011000  7.400   
1                      0.280                         0.012000  7.400   
2                      0.290                         0.012000  7.400   
3                      0.280                         0.012000  7.400   
4                      0.280                         0.012000  7.400   
...                      ...                              ...    ...   
9508                   0.209                         0.008467  7.300   
9509                   0.209                         0.008467  7.300   
9510                   0.209                         0.008467  7.300   
9511                   0.210                         0.008500  7.275   
9512                   0.209                         0.008467  7.200   

      Temperature (°C)  Total Nitrogen (mg/L)  Total Phosphorus (mg/L)  \
0                  7.4               0.410000                 0.017000   
1                  7.3               0.416667                 0.019667   
2                  7.3               0.440000                 0.019000   
3                  7.3               0.416667                 0.019667   
4                  7.3               0.416667                 0.019667   
...                ...                    ...                      ...   
9508              10.4               0.359000                 0.017300   
9509              10.4               0.359000                 0.017300   
9510              10.4               0.359000                 0.017300   
9511              10.4               0.359000                 0.017700   
9512              10.4               0.359000                 0.017300   

             WQI  WQ  
0      94.891147   4  
1      98.699450   4  
2     101.553997   5  
3      98.722325   4  
4      98.721299   4  
...          ...  ..  
9508   73.585895   2  
9509   73.575930   2  
9510   73.565999   2  
9511   73.995892   2  
9512   73.571772   2  

[9513 rows x 13 columns]

In [7]:
import numpy as np

In [43]:
WQI_Conditions = [
    (Big_Lake_df['WQI'] <= 25),
    (Big_Lake_df['WQI'] >= 26) & (Big_Lake_df['WQI'] <= 50),
    (Big_Lake_df['WQI'] >= 51) & (Big_Lake_df['WQI'] <= 75),
    (Big_Lake_df['WQI'] >= 76) & (Big_Lake_df['WQI'] <= 90),
    (Big_Lake_df['WQI'] >= 91) & (Big_Lake_df['WQI'] <= 100), 
    (Big_Lake_df['WQI'] > 101)
]

WQI_Categories = ['0', '1', '2', '3', '4', '5']

Big_Lake_df['WQ'] = np.select(WQI_Conditions, WQI_Categories) 

Big_Lake_df.head(50)

Big_Lake_df['WQ'].value_counts()


5    3312
2    2084
0    1138
3    1099
4     965
1     915
Name: WQ, dtype: int64

In [9]:
# Export csv file 

path = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Resources/Output/Big_Lake.csv"
Big_Lake_df.to_csv(path, index=False)

## Set Up Logistic Regression Model

In [119]:
# Import dependencies for ML
import pandas as pd
from sklearn import utils
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [120]:
# Seperate the Features (X) from the Target (y)
y = Big_Lake_df['WQ']

# Drop 'WQI'/'WQ' because those are outputs
X = Big_Lake_df.drop(['WQI', 'WQ', 'CollectDate'], axis='columns')

In [121]:
# Split our data into training and testing 
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,random_state=78)
                                                    
# Print X_test_shape                                                    
X_test.shape

(2379, 10)

In [135]:
# Print y_train
y_train


2834    2
9044    4
5009    5
2561    3
4670    4
       ..
6249    5
4136    5
6039    4
470     2
6853    1
Name: WQ, Length: 7134, dtype: object

In [136]:
# Check for y_train value counts in each categorical
y_train.value_counts()

5    2484
2    1563
0     833
3     831
4     719
1     704
Name: WQ, dtype: int64

In [123]:
# Print y_tes
y_test

5183    4
6013    2
4323    4
489     5
149     5
       ..
2274    5
2911    5
6223    5
7587    1
6       5
Name: WQ, Length: 2379, dtype: object

In [124]:
# Create a Logistic Regression Model 
# For multiclass problems, only ‘newton-cg’, ‘sag’, ‘saga’ and ‘lbfgs’ handle multinomial loss
# 'lbfgs' has error so switching to 'newton-cg'
classifier = LogisticRegression(solver='newton-cg', random_state=0)
classifier

LogisticRegression(random_state=0, solver='newton-cg')

In [125]:
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0, solver='newton-cg')

In [127]:
# Convert y values to categorical values
lab = preprocessing.LabelEncoder()
y_transformed = lab.fit_transform(y_train)

In [128]:
# View transformed values
print(y_transformed)

[2 4 5 ... 4 2 1]


In [129]:
# Fit (train) or model using the training data including y_trainsformed
classifier.fit(X_train, y_transformed)

LogisticRegression(random_state=0, solver='newton-cg')

In [130]:
# Prediction outcomes for test data set 
predictions = classifier.predict(X_test)

results = pd.DataFrame({"Prediction": predictions, "Actual": y_test}).reset_index(drop=True)
results.head(20)

Prediction Actual
0            4      4
1            2      2
2            5      4
3            5      5
4            5      5
5            3      3
6            5      5
7            2      2
8            5      4
9            5      4
10           2      0
11           2      3
12           5      5
13           2      1
14           3      3
15           2      4
16           2      2
17           5      5
18           0      1
19           0      0

In [131]:
# Print accuracy score 
print(accuracy_score(lab.fit_transform(y_test), predictions))

0.669609079445145


In [133]:
# Print total mean value of coefficient
np.mean(classifier.coef_)

3.233043462576764e-13

In [132]:
# Print mean of absolute value for each parameters
# See the coefficient of each parameter with WQI
np.mean(np.abs(classifier.coef_), 0)

array([2.84018458e+00, 6.15087902e-03, 5.37641371e-02, 4.79989819e-03,
       9.48488479e+00, 5.17781085e-01, 1.26093073e-01, 5.42234107e-02,
       6.32264247e+00, 9.98319878e-01])

In [139]:
# Calculating the confusion matrix.
cm = confusion_matrix(lab.fit_transform(y_test), predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1", "Actual 2", "Actual 3", "Actual 4", "Actual 5"],
    columns=["Predicted 0", "Predicted 1", "Predicted 2", "Predicted 3", "Predicted 4", "Predicted 5"])

cm_df

Predicted 0  Predicted 1  Predicted 2  Predicted 3  Predicted 4  \
Actual 0          152           51           45           11            2   
Actual 1          108           34           69            0            0   
Actual 2           10            4          504            3            0   
Actual 3            2            0          151           67           34   
Actual 4            0            0           37           17           19   
Actual 5            0            1           10            0            0   

          Predicted 5  
Actual 0           44  
Actual 1            0  
Actual 2            0  
Actual 3           14  
Actual 4          173  
Actual 5          817

In [140]:
# Print confusion matrix table 
confusion_matrix(lab.fit_transform(y_test), predictions)

array([[152,  51,  45,  11,   2,  44],
       [108,  34,  69,   0,   0,   0],
       [ 10,   4, 504,   3,   0,   0],
       [  2,   0, 151,  67,  34,  14],
       [  0,   0,  37,  17,  19, 173],
       [  0,   1,  10,   0,   0, 817]])

In [143]:
# Calculating the accuracy score.
acc_score = accuracy_score(lab.fit_transform(y_test), predictions)# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(lab.fit_transform(y_test), predictions))

Confusion Matrix


Predicted 0  Predicted 1  Predicted 2  Predicted 3  Predicted 4  \
Actual 0          152           51           45           11            2   
Actual 1          108           34           69            0            0   
Actual 2           10            4          504            3            0   
Actual 3            2            0          151           67           34   
Actual 4            0            0           37           17           19   
Actual 5            0            1           10            0            0   

          Predicted 5  
Actual 0           44  
Actual 1            0  
Actual 2            0  
Actual 3           14  
Actual 4          173  
Actual 5          817

Accuracy Score : 0.669609079445145
Classification Report
              precision    recall  f1-score   support

           0       0.56      0.50      0.53       305
           1       0.38      0.16      0.23       211
           2       0.62      0.97      0.75       521
           3       0.68      0.25      0.37       268
           4       0.35      0.08      0.13       246
           5       0.78      0.99      0.87       828

    accuracy                           0.67      2379
   macro avg       0.56      0.49      0.48      2379
weighted avg       0.62      0.67      0.61      2379

