## Random Forest

In [6]:
# Import descrepancies
import pandas as pd 
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [2]:
# Load the file data into the path
file_path = "/Users/linghoang/UCBBootcamp/DataClass/GroupProject/Final_Project_UCB_Bootcamp/Ritu_Gothwal/Resources_Ritu/Big_lake_Sammamish.csv"

# Load the file_path data into dataframe
Big_Lake_df = pd.read_csv(file_path)

# Show the WQ dataframe 
Big_Lake_df.head(10)

Unnamed: 0 CollectDate  Ammmonia Nitrogen (mg/L)  Conductivity (µmhos/cm)  \
0           0  1994-01-06                      0.02                    103.0   
1           1  1994-01-06                      0.02                    104.0   
2           2  1994-01-06                      0.02                    102.0   
3           3  1994-01-06                      0.02                    105.0   
4           4  1994-01-06                      0.02                    104.0   
5           5  1994-01-06                      0.02                    103.0   
6           6  1994-02-14                      0.02                    102.5   
7           7  1994-02-14                      0.02                    103.9   
8           8  1994-02-14                      0.02                    105.0   
9           9  1994-02-14                      0.02                    105.2   

   Dissolved Oxygen (mg/L)  Fecal Coliform (CFU/100ml)  \
0                     9.15                         1.0   
1                     8.98                         1.0   
2                     9.00                         1.0   
3                     9.21                         1.0   
4                     9.20                         1.0   
5                     9.19                         1.0   
6                    10.81                         7.0   
7                    10.71                         7.0   
8                    10.71                         7.0   
9                    10.65                         7.0   

   Nitrate Nitrite (mg/L)  Orthophosphate Phosphate (mg/L)   pH  \
0                0.270000                            0.011  7.4   
1                0.280000                            0.012  7.4   
2                0.290000                            0.012  7.4   
3                0.280000                            0.012  7.4   
4                0.280000                            0.012  7.4   
5                0.280000                            0.013  7.4   
6                0.310000                            0.009  7.4   
7                0.296667                            0.009  7.4   
8                0.260000                            0.009  7.4   
9                0.296667                            0.009  7.4   

   Temperature (°C)  Total Nitrogen (mg/L)  Total Phosphorus (mg/L)  \
0               7.4               0.410000                 0.017000   
1               7.3               0.416667                 0.019667   
2               7.3               0.440000                 0.019000   
3               7.3               0.416667                 0.019667   
4               7.3               0.416667                 0.019667   
5               7.3               0.400000                 0.023000   
6               6.5               0.470000                 0.030000   
7               6.5               0.500000                 0.036000   
8               6.5               0.530000                 0.049000   
9               6.5               0.500000                 0.036000   

          WQI  
0   94.891147  
1   98.699450  
2  101.553997  
3   98.722325  
4   98.721299  
5   99.698928  
6  111.025363  
7  108.874964  
8  101.827577  
9  108.869049

In [3]:
Big_Lake_df.columns

Index(['Unnamed: 0', 'CollectDate', 'Ammmonia Nitrogen (mg/L)',
       'Conductivity (µmhos/cm)', 'Dissolved Oxygen (mg/L)',
       'Fecal Coliform (CFU/100ml)', 'Nitrate Nitrite (mg/L)',
       'Orthophosphate Phosphate (mg/L)', 'pH', 'Temperature (°C)',
       'Total Nitrogen (mg/L)', 'Total Phosphorus (mg/L)', 'WQI'],
      dtype='object')

In [4]:
# Drop column 'Unnamed: 0' 
Big_Lake_df = Big_Lake_df.drop(columns=["Unnamed: 0"])

In [5]:
Big_Lake_df

CollectDate  Ammmonia Nitrogen (mg/L)  Conductivity (µmhos/cm)  \
0     1994-01-06                      0.02                   103.00   
1     1994-01-06                      0.02                   104.00   
2     1994-01-06                      0.02                   102.00   
3     1994-01-06                      0.02                   105.00   
4     1994-01-06                      0.02                   104.00   
...          ...                       ...                      ...   
9508  2008-12-09                      0.01                   103.00   
9509  2008-12-09                      0.01                   102.00   
9510  2008-12-09                      0.01                   102.00   
9511  2008-12-09                      0.01                   102.25   
9512  2008-12-09                      0.01                   102.00   

      Dissolved Oxygen (mg/L)  Fecal Coliform (CFU/100ml)  \
0                        9.15                         1.0   
1                        8.98                         1.0   
2                        9.00                         1.0   
3                        9.21                         1.0   
4                        9.20                         1.0   
...                       ...                         ...   
9508                     8.00                        37.0   
9509                     7.90                        37.0   
9510                     7.80                        37.0   
9511                     7.90                        37.0   
9512                     7.90                        37.0   

      Nitrate Nitrite (mg/L)  Orthophosphate Phosphate (mg/L)     pH  \
0                      0.270                         0.011000  7.400   
1                      0.280                         0.012000  7.400   
2                      0.290                         0.012000  7.400   
3                      0.280                         0.012000  7.400   
4                      0.280                         0.012000  7.400   
...                      ...                              ...    ...   
9508                   0.209                         0.008467  7.300   
9509                   0.209                         0.008467  7.300   
9510                   0.209                         0.008467  7.300   
9511                   0.210                         0.008500  7.275   
9512                   0.209                         0.008467  7.200   

      Temperature (°C)  Total Nitrogen (mg/L)  Total Phosphorus (mg/L)  \
0                  7.4               0.410000                 0.017000   
1                  7.3               0.416667                 0.019667   
2                  7.3               0.440000                 0.019000   
3                  7.3               0.416667                 0.019667   
4                  7.3               0.416667                 0.019667   
...                ...                    ...                      ...   
9508              10.4               0.359000                 0.017300   
9509              10.4               0.359000                 0.017300   
9510              10.4               0.359000                 0.017300   
9511              10.4               0.359000                 0.017700   
9512              10.4               0.359000                 0.017300   

             WQI  
0      94.891147  
1      98.699450  
2     101.553997  
3      98.722325  
4      98.721299  
...          ...  
9508   73.585895  
9509   73.575930  
9510   73.565999  
9511   73.995892  
9512   73.571772  

[9513 rows x 12 columns]

In [7]:
# Converting WQI data into index based on different water quality. 

WQI_Conditions = [
    (Big_Lake_df['WQI'] <= 25),
    (Big_Lake_df['WQI'] >= 26) & (Big_Lake_df['WQI'] <= 50),
    (Big_Lake_df['WQI'] >= 51) & (Big_Lake_df['WQI'] <= 75),
    (Big_Lake_df['WQI'] >= 76) & (Big_Lake_df['WQI'] <= 90),
    (Big_Lake_df['WQI'] >= 91) & (Big_Lake_df['WQI'] <= 100), 
    (Big_Lake_df['WQI'] > 101)
]

WQI_Categories = ['0', '1', '2', '3', '4', '5']

Big_Lake_df['WQ'] = np.select(WQI_Conditions, WQI_Categories) 

Big_Lake_df.head(50)

CollectDate  Ammmonia Nitrogen (mg/L)  Conductivity (µmhos/cm)  \
0   1994-01-06                      0.02                    103.0   
1   1994-01-06                      0.02                    104.0   
2   1994-01-06                      0.02                    102.0   
3   1994-01-06                      0.02                    105.0   
4   1994-01-06                      0.02                    104.0   
5   1994-01-06                      0.02                    103.0   
6   1994-02-14                      0.02                    102.5   
7   1994-02-14                      0.02                    103.9   
8   1994-02-14                      0.02                    105.0   
9   1994-02-14                      0.02                    105.2   
10  1994-02-14                      0.02                    105.2   
11  1994-02-14                      0.02                    105.5   
12  1994-03-08                      0.02                    103.4   
13  1994-03-08                      0.02                    104.0   
14  1994-03-08                      0.02                    105.1   
15  1994-03-08                      0.02                    105.3   
16  1994-03-08                      0.02                    105.9   
17  1994-03-08                      0.02                    105.3   
18  1994-03-22                      0.02                    104.0   
19  1994-03-22                      0.02                    105.3   
20  1994-03-22                      0.02                    105.9   
21  1994-03-22                      0.02                    106.2   
22  1994-03-22                      0.02                    106.3   
23  1994-03-22                      0.02                    106.5   
24  1994-04-05                      0.02                    103.7   
25  1994-04-05                      0.02                    104.2   
26  1994-04-05                      0.02                    103.3   
27  1994-04-05                      0.02                    103.3   
28  1994-04-05                      0.02                    103.7   
29  1994-04-05                      0.02                    103.9   
30  1994-04-19                      0.02                    104.5   
31  1994-04-19                      0.02                    105.0   
32  1994-04-19                      0.02                    103.9   
33  1994-04-19                      0.02                    103.6   
34  1994-04-19                      0.02                    104.1   
35  1994-04-19                      0.02                    104.1   
36  1994-05-03                      0.02                    108.3   
37  1994-05-03                      0.02                    108.5   
38  1994-05-03                      0.02                    107.0   
39  1994-05-03                      0.02                    106.6   
40  1994-05-03                      0.02                    106.3   
41  1994-05-03                      0.02                    106.4   
42  1994-05-24                      0.02                    114.1   
43  1994-05-24                      0.02                    114.2   
44  1994-05-24                      0.02                    113.7   
45  1994-05-24                      0.02                    113.4   
46  1994-05-24                      0.02                    113.1   
47  1994-05-24                      0.02                    112.4   
48  1994-05-24                      0.02                    112.1   
49  1994-05-24                      0.02                    111.5   

    Dissolved Oxygen (mg/L)  Fecal Coliform (CFU/100ml)  \
0                      9.15                         1.0   
1                      8.98                         1.0   
2                      9.00                         1.0   
3                      9.21                         1.0   
4                      9.20                         1.0   
5                      9.19                         1.0   
6                     10.81                         7.0   
7          

In [8]:
# Initial imports for machine learning 
# Initials imports
import pandas as pd
from pathlib import Path
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [9]:
# Preprocess data
# Define the features set
X = Big_Lake_df.copy()
X = X.drop(['WQ','CollectDate'], axis='columns')
X.head()

Ammmonia Nitrogen (mg/L)  Conductivity (µmhos/cm)  Dissolved Oxygen (mg/L)  \
0                      0.02                    103.0                     9.15   
1                      0.02                    104.0                     8.98   
2                      0.02                    102.0                     9.00   
3                      0.02                    105.0                     9.21   
4                      0.02                    104.0                     9.20   

   Fecal Coliform (CFU/100ml)  Nitrate Nitrite (mg/L)  \
0                         1.0                    0.27   
1                         1.0                    0.28   
2                         1.0                    0.29   
3                         1.0                    0.28   
4                         1.0                    0.28   

   Orthophosphate Phosphate (mg/L)   pH  Temperature (°C)  \
0                            0.011  7.4               7.4   
1                            0.012  7.4               7.3   
2                            0.012  7.4               7.3   
3                            0.012  7.4               7.3   
4                            0.012  7.4               7.3   

   Total Nitrogen (mg/L)  Total Phosphorus (mg/L)         WQI  
0               0.410000                 0.017000   94.891147  
1               0.416667                 0.019667   98.699450  
2               0.440000                 0.019000  101.553997  
3               0.416667                 0.019667   98.722325  
4               0.416667                 0.019667   98.721299

In [10]:
# Define the target set.
y = Big_Lake_df["WQ"].ravel()
y[:20]

array(['4', '4', '5', '4', '4', '4', '5', '5', '5', '5', '5', '5', '4',
       '5', '5', '5', '5', '5', '5', '5'], dtype=object)

In [11]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [12]:
# Creating a StandardScaler instance.
scaler = StandardScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train)

# Scaling the data.
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [13]:
# Fit the random forest classidier
# Create a random forest classifier.
rf_model = RandomForestClassifier(n_estimators=128, random_state=78) 

In [14]:
# Fitting the model
rf_model = rf_model.fit(X_train_scaled, y_train)

In [15]:
# Making predictions using the testing data.
predictions = rf_model.predict(X_test_scaled)

In [16]:
# Calculating the confusion matrix.
cm = confusion_matrix(y_test, predictions)

# Create a DataFrame from the confusion matrix.
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1", "Actual 2", "Actual 3", "Actual 4", "Actual 5"],
    columns=["Predicted 0", "Predicted 1", "Predicted 2", "Predicted 3", "Predicted 4", "Predicted 5"])

cm_df

Predicted 0  Predicted 1  Predicted 2  Predicted 3  Predicted 4  \
Actual 0          297            1            1            1            5   
Actual 1            0          211            0            0            0   
Actual 2            0            0          521            0            0   
Actual 3            1            0            0          267            0   
Actual 4            2            0            0            0          244   
Actual 5            0            0            0            0            0   

          Predicted 5  
Actual 0            0  
Actual 1            0  
Actual 2            0  
Actual 3            0  
Actual 4            0  
Actual 5          828

In [17]:
print(cm)

[[297   1   1   1   5   0]
 [  0 211   0   0   0   0]
 [  0   0 521   0   0   0]
 [  1   0   0 267   0   0]
 [  2   0   0   0 244   0]
 [  0   0   0   0   0 828]]


In [18]:
# Calculating the accuracy score.
acc_score = accuracy_score(y_test, predictions)# Displaying results
print("Confusion Matrix")
display(cm_df)
print(f"Accuracy Score : {acc_score}")
print("Classification Report")
print(classification_report(y_test, predictions))

Confusion Matrix


Predicted 0  Predicted 1  Predicted 2  Predicted 3  Predicted 4  \
Actual 0          297            1            1            1            5   
Actual 1            0          211            0            0            0   
Actual 2            0            0          521            0            0   
Actual 3            1            0            0          267            0   
Actual 4            2            0            0            0          244   
Actual 5            0            0            0            0            0   

          Predicted 5  
Actual 0            0  
Actual 1            0  
Actual 2            0  
Actual 3            0  
Actual 4            0  
Actual 5          828

Accuracy Score : 0.9953762084909626
Classification Report
              precision    recall  f1-score   support

           0       0.99      0.97      0.98       305
           1       1.00      1.00      1.00       211
           2       1.00      1.00      1.00       521
           3       1.00      1.00      1.00       268
           4       0.98      0.99      0.99       246
           5       1.00      1.00      1.00       828

    accuracy                           1.00      2379
   macro avg       0.99      0.99      0.99      2379
weighted avg       1.00      1.00      1.00      2379



In [19]:
# Calculate feature importance in the Random Forest model.
importances = rf_model.feature_importances_
importances

array([0.02313985, 0.01583714, 0.01482253, 0.00585715, 0.27516639,
       0.02006406, 0.00719915, 0.02465035, 0.13500177, 0.01927947,
       0.45898214])

In [20]:
# We can sort the features by their importance.
sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)

[(0.4589821366825156, 'WQI'),
 (0.275166390062254, 'Nitrate Nitrite (mg/L)'),
 (0.13500176973412756, 'Total Nitrogen (mg/L)'),
 (0.024650348775871325, 'Temperature (°C)'),
 (0.023139854614854436, 'Ammmonia Nitrogen (mg/L)'),
 (0.02006405591440785, 'Orthophosphate Phosphate (mg/L)'),
 (0.019279473936507106, 'Total Phosphorus (mg/L)'),
 (0.015837135240256383, 'Conductivity (µmhos/cm)'),
 (0.014822533951750405, 'Dissolved Oxygen (mg/L)'),
 (0.007199147407507705, 'pH'),
 (0.005857153679947582, 'Fecal Coliform (CFU/100ml)')]